# permissions for end users to view kingfishers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kingfisher-viewer-role
rules:
- apiGroups:
  - birds.github.com
  resources:
  - kingfishers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - birds.github.com
  resources:
  - kingfishers/status
  verbs:
  - get
